- name: Install Docker
  hosts: all
  gather_facts: no

  tasks:
  - name: Install Docker
    shell: curl -sLk https://releases.rancher.com/install-docker/{{ docker_version }}.sh | bash -
    args:
      warn: no