- name: Add/Update Docker Container
  hosts: all
  gather_facts: yes

  tasks:
  - name: Install EPEL Release and python-pip
    yum:
      name:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - python-pip
      enablerepo: "*"
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install python-pip
    apt:
      name: python-pip
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Install Docker
    command: curl -sLk https://releases.rancher.com/install-docker/{{ docker_version }}.sh | bash -
    when: install_docker == "yes"

  - name: Docker Python Module
    pip:
      name: docker

  - name: Create Docker Container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      state: "started"
      pull: "true"
      restart_policy: "{{ restart_policy }}"
      ports: "{{ port_map }}"
      volumes: "{{ volume_map }}"