- name: Add/Update Docker Container
  hosts: all
  gather_facts: no

  tasks:
  - name: Docker Python Module
    pip:
      name: docker

  - name: Create Docker Container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      state: "started"
      pull: "true"
      restart_policy: "{{ restart_policy }}"
      ports: "{{ port_map }}"
      volumes: "{{ volume_map }}"