- name: Add/Update Helm Chart Deployment
  hosts: all
  gather_facts: no

  tasks:
  - name: Deploy Helm Chart
    helm:
      host: "{{ tiller_host }}"
      chart:
        name: "{{ chart_name }}"
        version: "{{ chart_version }}"
        source:
          type: "repo"
          location: "{{ chart_repo }}"
          path: "{{ chart_path }}"
      state: present
      name: "{{ deployment_name }}"
      namespace: "{{ kube_namespace }}"