- name: Add/Update Helm Chart Deployment
  hosts: all
  gather_facts: no

  tasks:
  - name: Install Helm
    shell: curl -skL -X GET "https://raw.githubusercontent.com/helm/helm/master/scripts/get" | bash -
    args:
      warn: no

  - name: Install kubectl
    shell: curl -skL https://storage.googleapis.com/kubernetes-release/release/`curl -skL https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
    command: chmod +x /usr/local/bin/kubectl

  - name: Copy kubeconfig
    command: mkdir ~/.kube
    command: touch ~/.kube/config
    shell: echo "{{ KUBE_CONFIG }}" > ~/.kube/config

  - name: Helm init
    command: helm init --client-only

  - name: Add chart-repo ca authority
    shell: echo -n | openssl s_client -connect {{ chart_repo }}:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /usr/local/share/ca-certificates/{{ chart_repo }}.cert

  - name: Update ca authority
    command: update-ca-certificates

  - name: Add helm repo
    command: helm repo add {{ helm_repo }} https://{{ chart_repo }}/{{ repo_path }}
    when: private_repo == 0

  - name: Add helm repo
    command: helm repo add --username {{ repo_username }} --password {{ repo_password }} {{ helm_repo }} https://{{ chart_repo }}/{{ repo_path }}
    when: private_repo == 1

  - name: Update helm repos
    command: helm repo update

  - name: Deploy Helm Chart
    command: helm upgrade --install {{ deployment_name }} {{ helm_repo }}/{{ chart_name }} --version {{ chart_version }} --namespace {{ kube_namespace }}
    register: helm_output

  - debug: msg="Helm Output:\n{{ helm_output.stdout }}"

  - debug: msg="Helm Error:\n{{ helm_output.stderr }}"
    # helm:
    #   host: "{{ tiller_host }}"
    #   chart:
    #     name: "{{ chart_name }}"
    #     version: "{{ chart_version }}"
    #     source:
    #       type: "repo"
    #       location: "{{ chart_repo }}"
    #       path: "{{ chart_path }}"
    #   state: present
    #   name: "{{ deployment_name }}"
    #   namespace: "{{ kube_namespace }}"
    # environment:
    #   SSL_CERT_DIR: /etc/ssl/certs
    #   SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    #   REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt