- name: Add/Update Helm Chart Deployment
  hosts: all
  gather_facts: yes

  tasks:
  - name: Install EPEL Release and python-pip
    yum:
      name:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - python-pip
      enablerepo: "*"
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install python-pip
    apt:
      name: python-pip
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Helm Python Module
    pip:
      name: pyhelm

  - name: Deploy Helm Chart
    helm:
      host: "localhost"
      chart:
        name: "{{ chart_name }}"
        version: "{{ chart_version }}"
      state: present
      name: "{{ deployment_name }}"
      namespace: "{{ kube_namespace }}"
    environment:
      SSL_CERT_DIR: /usr/lib/ssl/certs
      SSL_CERT_FILE: /usr/lib/ssl/certs/ca-certificates.crt

  # - name: Debug log
  #   environment:
  #     SSL_CERT_DIR: /usr/lib/ssl/certs
  #     SSL_CERT_FILE: /usr/lib/ssl/certs/ca-certificates.crt
  #   debug:
  #     msg: "{{ lookup('env','SSL_CERT_DIR') }} {{ lookup('env','SSL_CERT_FILE') }} is SSL CERT DIR"